//TYPES
export const TYPE_PROJECT = "PROJECT"
export const TYPE_RELEASE = "RELEASE"
export const TYPE_TASK = "TASK"
export const TYPE_USERSTORIE = "USERSTORIE"
export const TYPE_BUG = "BUG"

//TECHNICIAN TYPES
export const TECH_TYPE_MANAGER = "MANAGER"
export const TECH_TYPE_TECHNICIAN = "TECHNICIAN"
export const TECH_TYPE_TESTER = "TESTER"

//STATES
export const STATE_OPEN = "OPEN"
export const STATE_PLANNED = "PLANNED"
export const STATE_IN_PROGRESS = "IN_PROGRESS"
export const STATE_IN_TESTING = "IN_TESTING"
export const STATE_DONE = "DONE"

//COMPANY COORDS

export const COMPANY_COORDS_MAX_LAT = 41.6906537
export const COMPANY_COORDS_MIN_LAT = 41.6905204
export const COMPANY_COORDS_MAX_LNG = -8.8281911
export const COMPANY_COORDS_MIN_LNG = -8.8280342
